version: '3.8'
services:
  app:
    image: node:12-alpine
    command: sh -c "yarn install && yarn run dev"
    working_dir: /nodejs-postgresql-master
    ports:
      - "3000:3000"
    volumes:
      - ./:/nodejs-postgresql-master
    environment:
      - POSTGRES_USER:postgres
      - POSTGRES_PASSWORD:postgres
      - POSTGRES_DB:test
    depends_on:
      - db

  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=test
    ports:
      - '5432:5432'
    volumes:
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local